#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DasherStation.equipment
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="DasherStation3")]
	public partial class EquipmentDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEquipmentInformation(EquipmentInformation instance);
    partial void UpdateEquipmentInformation(EquipmentInformation instance);
    partial void DeleteEquipmentInformation(EquipmentInformation instance);
    #endregion
		
		public EquipmentDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipmentDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipmentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EquipmentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EquipmentInformation> EquipmentInformation
		{
			get
			{
				return this.GetTable<EquipmentInformation>();
			}
		}
	}
	
	[Table(Name="dbo.equipmentInformation")]
	public partial class EquipmentInformation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _no;
		
		private System.Nullable<long> _enId;
		
		private System.Nullable<long> _emId;
		
		private System.Nullable<long> _dId;
		
		private System.Nullable<long> _count;
		
		private string _registrationMark;
		
		private string _installationPosition;
		
		private System.Nullable<decimal> _sumPower;
		
		private string _addMethod;
		
		private System.Nullable<decimal> _primaryValue;
		
		private System.Nullable<decimal> _remainsValue;
		
		private System.Nullable<long> _depreciationYear;
		
		private System.Nullable<System.DateTime> _produceDate;
		
		private string _factoryNo;
		
		private string _contactMethod;
		
		private string _factoryAddress;
		
		private string _postCode;
		
		private string _workMan;
		
		private System.Nullable<decimal> _diameter;
		
		private System.Nullable<decimal> _height;
		
		private System.Nullable<System.DateTime> _beginUseTime;
		
		private string _contactMan;
		
		private string _producer;
		
		private System.Nullable<System.DateTime> _inputDate;
		
		private string _inputMan;
		
		private string _remark;
		
		private System.Nullable<long> _dId2;
		
		private string _kind;
		
		private System.Nullable<decimal> _proportionError;
		
		private System.Nullable<decimal> _totalMaterialWeight;
		
		private string _mark;
		
		private System.Nullable<decimal> _proportionError2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnnoChanging(string value);
    partial void OnnoChanged();
    partial void OnenIdChanging(System.Nullable<long> value);
    partial void OnenIdChanged();
    partial void OnemIdChanging(System.Nullable<long> value);
    partial void OnemIdChanged();
    partial void OndIdChanging(System.Nullable<long> value);
    partial void OndIdChanged();
    partial void OncountChanging(System.Nullable<long> value);
    partial void OncountChanged();
    partial void OnregistrationMarkChanging(string value);
    partial void OnregistrationMarkChanged();
    partial void OninstallationPositionChanging(string value);
    partial void OninstallationPositionChanged();
    partial void OnsumPowerChanging(System.Nullable<decimal> value);
    partial void OnsumPowerChanged();
    partial void OnaddMethodChanging(string value);
    partial void OnaddMethodChanged();
    partial void OnprimaryValueChanging(System.Nullable<decimal> value);
    partial void OnprimaryValueChanged();
    partial void OnremainsValueChanging(System.Nullable<decimal> value);
    partial void OnremainsValueChanged();
    partial void OndepreciationYearChanging(System.Nullable<long> value);
    partial void OndepreciationYearChanged();
    partial void OnproduceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnproduceDateChanged();
    partial void OnfactoryNoChanging(string value);
    partial void OnfactoryNoChanged();
    partial void OncontactMethodChanging(string value);
    partial void OncontactMethodChanged();
    partial void OnfactoryAddressChanging(string value);
    partial void OnfactoryAddressChanged();
    partial void OnpostCodeChanging(string value);
    partial void OnpostCodeChanged();
    partial void OnworkManChanging(string value);
    partial void OnworkManChanged();
    partial void OndiameterChanging(System.Nullable<decimal> value);
    partial void OndiameterChanged();
    partial void OnheightChanging(System.Nullable<decimal> value);
    partial void OnheightChanged();
    partial void OnbeginUseTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnbeginUseTimeChanged();
    partial void OncontactManChanging(string value);
    partial void OncontactManChanged();
    partial void OnproducerChanging(string value);
    partial void OnproducerChanged();
    partial void OninputDateChanging(System.Nullable<System.DateTime> value);
    partial void OninputDateChanged();
    partial void OninputManChanging(string value);
    partial void OninputManChanged();
    partial void OnremarkChanging(string value);
    partial void OnremarkChanged();
    partial void OndId2Changing(System.Nullable<long> value);
    partial void OndId2Changed();
    partial void OnkindChanging(string value);
    partial void OnkindChanged();
    partial void OnproportionErrorChanging(System.Nullable<decimal> value);
    partial void OnproportionErrorChanged();
    partial void OntotalMaterialWeightChanging(System.Nullable<decimal> value);
    partial void OntotalMaterialWeightChanged();
    partial void OnmarkChanging(string value);
    partial void OnmarkChanged();
    partial void OnproportionError2Changing(System.Nullable<decimal> value);
    partial void OnproportionError2Changed();
    #endregion
		
		public EquipmentInformation()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_no", DbType="VarChar(200)")]
		public string no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this.OnnoChanging(value);
					this.SendPropertyChanging();
					this._no = value;
					this.SendPropertyChanged("no");
					this.OnnoChanged();
				}
			}
		}
		
		[Column(Storage="_enId", DbType="BigInt")]
		public System.Nullable<long> enId
		{
			get
			{
				return this._enId;
			}
			set
			{
				if ((this._enId != value))
				{
					this.OnenIdChanging(value);
					this.SendPropertyChanging();
					this._enId = value;
					this.SendPropertyChanged("enId");
					this.OnenIdChanged();
				}
			}
		}
		
		[Column(Storage="_emId", DbType="BigInt")]
		public System.Nullable<long> emId
		{
			get
			{
				return this._emId;
			}
			set
			{
				if ((this._emId != value))
				{
					this.OnemIdChanging(value);
					this.SendPropertyChanging();
					this._emId = value;
					this.SendPropertyChanged("emId");
					this.OnemIdChanged();
				}
			}
		}
		
		[Column(Storage="_dId", DbType="BigInt")]
		public System.Nullable<long> dId
		{
			get
			{
				return this._dId;
			}
			set
			{
				if ((this._dId != value))
				{
					this.OndIdChanging(value);
					this.SendPropertyChanging();
					this._dId = value;
					this.SendPropertyChanged("dId");
					this.OndIdChanged();
				}
			}
		}
		
		[Column(Storage="_count", DbType="BigInt")]
		public System.Nullable<long> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this.OncountChanging(value);
					this.SendPropertyChanging();
					this._count = value;
					this.SendPropertyChanged("count");
					this.OncountChanged();
				}
			}
		}
		
		[Column(Storage="_registrationMark", DbType="VarChar(100)")]
		public string registrationMark
		{
			get
			{
				return this._registrationMark;
			}
			set
			{
				if ((this._registrationMark != value))
				{
					this.OnregistrationMarkChanging(value);
					this.SendPropertyChanging();
					this._registrationMark = value;
					this.SendPropertyChanged("registrationMark");
					this.OnregistrationMarkChanged();
				}
			}
		}
		
		[Column(Storage="_installationPosition", DbType="VarChar(50)")]
		public string installationPosition
		{
			get
			{
				return this._installationPosition;
			}
			set
			{
				if ((this._installationPosition != value))
				{
					this.OninstallationPositionChanging(value);
					this.SendPropertyChanging();
					this._installationPosition = value;
					this.SendPropertyChanged("installationPosition");
					this.OninstallationPositionChanged();
				}
			}
		}
		
		[Column(Storage="_sumPower", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> sumPower
		{
			get
			{
				return this._sumPower;
			}
			set
			{
				if ((this._sumPower != value))
				{
					this.OnsumPowerChanging(value);
					this.SendPropertyChanging();
					this._sumPower = value;
					this.SendPropertyChanged("sumPower");
					this.OnsumPowerChanged();
				}
			}
		}
		
		[Column(Storage="_addMethod", DbType="VarChar(50)")]
		public string addMethod
		{
			get
			{
				return this._addMethod;
			}
			set
			{
				if ((this._addMethod != value))
				{
					this.OnaddMethodChanging(value);
					this.SendPropertyChanging();
					this._addMethod = value;
					this.SendPropertyChanged("addMethod");
					this.OnaddMethodChanged();
				}
			}
		}
		
		[Column(Storage="_primaryValue", DbType="Money")]
		public System.Nullable<decimal> primaryValue
		{
			get
			{
				return this._primaryValue;
			}
			set
			{
				if ((this._primaryValue != value))
				{
					this.OnprimaryValueChanging(value);
					this.SendPropertyChanging();
					this._primaryValue = value;
					this.SendPropertyChanged("primaryValue");
					this.OnprimaryValueChanged();
				}
			}
		}
		
		[Column(Storage="_remainsValue", DbType="Money")]
		public System.Nullable<decimal> remainsValue
		{
			get
			{
				return this._remainsValue;
			}
			set
			{
				if ((this._remainsValue != value))
				{
					this.OnremainsValueChanging(value);
					this.SendPropertyChanging();
					this._remainsValue = value;
					this.SendPropertyChanged("remainsValue");
					this.OnremainsValueChanged();
				}
			}
		}
		
		[Column(Storage="_depreciationYear", DbType="BigInt")]
		public System.Nullable<long> depreciationYear
		{
			get
			{
				return this._depreciationYear;
			}
			set
			{
				if ((this._depreciationYear != value))
				{
					this.OndepreciationYearChanging(value);
					this.SendPropertyChanging();
					this._depreciationYear = value;
					this.SendPropertyChanged("depreciationYear");
					this.OndepreciationYearChanged();
				}
			}
		}
		
		[Column(Storage="_produceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> produceDate
		{
			get
			{
				return this._produceDate;
			}
			set
			{
				if ((this._produceDate != value))
				{
					this.OnproduceDateChanging(value);
					this.SendPropertyChanging();
					this._produceDate = value;
					this.SendPropertyChanged("produceDate");
					this.OnproduceDateChanged();
				}
			}
		}
		
		[Column(Storage="_factoryNo", DbType="VarChar(50)")]
		public string factoryNo
		{
			get
			{
				return this._factoryNo;
			}
			set
			{
				if ((this._factoryNo != value))
				{
					this.OnfactoryNoChanging(value);
					this.SendPropertyChanging();
					this._factoryNo = value;
					this.SendPropertyChanged("factoryNo");
					this.OnfactoryNoChanged();
				}
			}
		}
		
		[Column(Storage="_contactMethod", DbType="VarChar(50)")]
		public string contactMethod
		{
			get
			{
				return this._contactMethod;
			}
			set
			{
				if ((this._contactMethod != value))
				{
					this.OncontactMethodChanging(value);
					this.SendPropertyChanging();
					this._contactMethod = value;
					this.SendPropertyChanged("contactMethod");
					this.OncontactMethodChanged();
				}
			}
		}
		
		[Column(Storage="_factoryAddress", DbType="VarChar(50)")]
		public string factoryAddress
		{
			get
			{
				return this._factoryAddress;
			}
			set
			{
				if ((this._factoryAddress != value))
				{
					this.OnfactoryAddressChanging(value);
					this.SendPropertyChanging();
					this._factoryAddress = value;
					this.SendPropertyChanged("factoryAddress");
					this.OnfactoryAddressChanged();
				}
			}
		}
		
		[Column(Storage="_postCode", DbType="VarChar(50)")]
		public string postCode
		{
			get
			{
				return this._postCode;
			}
			set
			{
				if ((this._postCode != value))
				{
					this.OnpostCodeChanging(value);
					this.SendPropertyChanging();
					this._postCode = value;
					this.SendPropertyChanged("postCode");
					this.OnpostCodeChanged();
				}
			}
		}
		
		[Column(Storage="_workMan", DbType="VarChar(50)")]
		public string workMan
		{
			get
			{
				return this._workMan;
			}
			set
			{
				if ((this._workMan != value))
				{
					this.OnworkManChanging(value);
					this.SendPropertyChanging();
					this._workMan = value;
					this.SendPropertyChanged("workMan");
					this.OnworkManChanged();
				}
			}
		}
		
		[Column(Storage="_diameter", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> diameter
		{
			get
			{
				return this._diameter;
			}
			set
			{
				if ((this._diameter != value))
				{
					this.OndiameterChanging(value);
					this.SendPropertyChanging();
					this._diameter = value;
					this.SendPropertyChanged("diameter");
					this.OndiameterChanged();
				}
			}
		}
		
		[Column(Storage="_height", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[Column(Storage="_beginUseTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> beginUseTime
		{
			get
			{
				return this._beginUseTime;
			}
			set
			{
				if ((this._beginUseTime != value))
				{
					this.OnbeginUseTimeChanging(value);
					this.SendPropertyChanging();
					this._beginUseTime = value;
					this.SendPropertyChanged("beginUseTime");
					this.OnbeginUseTimeChanged();
				}
			}
		}
		
		[Column(Storage="_contactMan", DbType="VarChar(50)")]
		public string contactMan
		{
			get
			{
				return this._contactMan;
			}
			set
			{
				if ((this._contactMan != value))
				{
					this.OncontactManChanging(value);
					this.SendPropertyChanging();
					this._contactMan = value;
					this.SendPropertyChanged("contactMan");
					this.OncontactManChanged();
				}
			}
		}
		
		[Column(Storage="_producer", DbType="VarChar(50)")]
		public string producer
		{
			get
			{
				return this._producer;
			}
			set
			{
				if ((this._producer != value))
				{
					this.OnproducerChanging(value);
					this.SendPropertyChanging();
					this._producer = value;
					this.SendPropertyChanged("producer");
					this.OnproducerChanged();
				}
			}
		}
		
		[Column(Storage="_inputDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> inputDate
		{
			get
			{
				return this._inputDate;
			}
			set
			{
				if ((this._inputDate != value))
				{
					this.OninputDateChanging(value);
					this.SendPropertyChanging();
					this._inputDate = value;
					this.SendPropertyChanged("inputDate");
					this.OninputDateChanged();
				}
			}
		}
		
		[Column(Storage="_inputMan", DbType="VarChar(50)")]
		public string inputMan
		{
			get
			{
				return this._inputMan;
			}
			set
			{
				if ((this._inputMan != value))
				{
					this.OninputManChanging(value);
					this.SendPropertyChanging();
					this._inputMan = value;
					this.SendPropertyChanged("inputMan");
					this.OninputManChanged();
				}
			}
		}
		
		[Column(Storage="_remark", DbType="VarChar(500)")]
		public string remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				if ((this._remark != value))
				{
					this.OnremarkChanging(value);
					this.SendPropertyChanging();
					this._remark = value;
					this.SendPropertyChanged("remark");
					this.OnremarkChanged();
				}
			}
		}
		
		[Column(Storage="_dId2", DbType="BigInt")]
		public System.Nullable<long> dId2
		{
			get
			{
				return this._dId2;
			}
			set
			{
				if ((this._dId2 != value))
				{
					this.OndId2Changing(value);
					this.SendPropertyChanging();
					this._dId2 = value;
					this.SendPropertyChanged("dId2");
					this.OndId2Changed();
				}
			}
		}
		
		[Column(Storage="_kind", DbType="VarChar(50)")]
		public string kind
		{
			get
			{
				return this._kind;
			}
			set
			{
				if ((this._kind != value))
				{
					this.OnkindChanging(value);
					this.SendPropertyChanging();
					this._kind = value;
					this.SendPropertyChanged("kind");
					this.OnkindChanged();
				}
			}
		}
		
		[Column(Storage="_proportionError", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> proportionError
		{
			get
			{
				return this._proportionError;
			}
			set
			{
				if ((this._proportionError != value))
				{
					this.OnproportionErrorChanging(value);
					this.SendPropertyChanging();
					this._proportionError = value;
					this.SendPropertyChanged("proportionError");
					this.OnproportionErrorChanged();
				}
			}
		}
		
		[Column(Storage="_totalMaterialWeight", DbType="Decimal(14,2)")]
		public System.Nullable<decimal> totalMaterialWeight
		{
			get
			{
				return this._totalMaterialWeight;
			}
			set
			{
				if ((this._totalMaterialWeight != value))
				{
					this.OntotalMaterialWeightChanging(value);
					this.SendPropertyChanging();
					this._totalMaterialWeight = value;
					this.SendPropertyChanged("totalMaterialWeight");
					this.OntotalMaterialWeightChanged();
				}
			}
		}
		
		[Column(Storage="_mark", DbType="VarChar(50)")]
		public string mark
		{
			get
			{
				return this._mark;
			}
			set
			{
				if ((this._mark != value))
				{
					this.OnmarkChanging(value);
					this.SendPropertyChanging();
					this._mark = value;
					this.SendPropertyChanged("mark");
					this.OnmarkChanged();
				}
			}
		}
		
		[Column(Storage="_proportionError2", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> proportionError2
		{
			get
			{
				return this._proportionError2;
			}
			set
			{
				if ((this._proportionError2 != value))
				{
					this.OnproportionError2Changing(value);
					this.SendPropertyChanging();
					this._proportionError2 = value;
					this.SendPropertyChanged("proportionError2");
					this.OnproportionError2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
