<?xml version="1.0" encoding="utf-8"?>
<Database Name="DasherStation" Class="MonitorDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.temperatureNo" Member="TemperatureNo">
    <Type Name="TemperatureNo">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="inputDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inputMan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="minTemperature" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="maxTemperature" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.flowmeterNo" Member="FlowmeterNo">
    <Type Name="FlowmeterNo">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inputDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inputMan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.liquidPositionNo" Member="LiquidPositionNo">
    <Type Name="LiquidPositionNo">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="no" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="inputDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="inputMan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="remark" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="minValue" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="maxValue" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>